name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 每天 00:00 自动运行
  push:
    branches:
      - main

permissions:
  contents: write # 一定要有 write 权限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # 不使用默认 GITHUB_TOKEN

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: genwilliam
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # 你在 Settings → Secrets → Actions 创建的 PAT
        run: |
          set -e
          cd dist
          git init
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Generate snake animation"
          git branch -M output
          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push -f origin output
