name: Update Stats PNG

on:
  schedule:
    - cron: "0 * * * *" # 每小时
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # 必须设为 false，否则会使用 GITHUB_TOKEN 登录
          fetch-depth: 0

      - name: Generate PNG
        run: |
          echo "这里执行你的生成图片脚本"

      - name: Commit and Push
        env:
          PAT: ${{ secrets.stars_generate }} # PAT token 名字
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Update stats PNG" || echo "No changes"

          # 使用 PAT 推送，而不是默认 GITHUB_TOKEN
          git push https://x-access-token:${PAT}@github.com/genwilliam/genwilliam.git
