name: Generate Stats PNG

on:
  schedule:
    - cron: "0 * * * *" # 每小时运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate PNG
        run: |
          mkdir -p assets
          curl -L -o assets/github-stats.png "https://github-readme-stats.vercel.app/api?username=genwilliam&show_icons=true&theme=gruvbox"
          curl -L -o assets/top-langs.png "https://github-readme-stats.vercel.app/api/top-langs/?username=genwilliam&layout=compact&theme=gruvbox"
          curl -L -o assets/trophy.png "https://github-profile-trophy.vercel.app/?username=genwilliam&theme=gruvbox"

      - name: Upload PNG as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest-assets
          path: assets
